language: python
python:
  - '3.6'
sudo: false

branches:
  only:
    - master

addons:
  code_climate:
    repo_token: e099e1a99c7c0d98c74a60860729f4c66e3e997ca71221e6681f4219772ede7d

install:
  - pip install -r requirements/base.txt

script:
  - coverage run --rcfile=coverage.cfg -m unittest discover ./tests
  - coverage report --rcfile=coverage.cfg

after_success:
- codeclimate-test-reporter
